# Generated by Django 4.2.1 on 2023-07-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_tester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseName', models.CharField(max_length=200)),
                ('expenseCost', models.CharField(max_length=200)),
                ('expenseFrequency', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
