# Generated by Django 4.2.1 on 2023-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_alter_appuser_groups_alter_appuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expenseCategory',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
