# Generated by Django 4.2.1 on 2023-07-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_expense_expensecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expenseCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
